Repository AY2425S1-CS2103-F12-1/tp, pull requests merged in 2024-10, with the labels that each got.

#31 Update non functional requirements
  docs/DeveloperGuide.md
Labels: type.Chore

#36 Remove Jean Doe
  docs/AboutUs.md
Labels: type.Chore, type.Bug

#30 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Chore

#78 Create Unit Tests for InsurancePlanFactory.java
  src/main/java/seedu/address/model/person/insurance/InsurancePlanFactory.java
  src/test/java/seedu/address/model/person/insurance/InsurancePlanFactoryTest.java
  src/test/java/seedu/address/model/person/insurance/InsurancePlanTest.java
Labels: priority.Medium

#127 Fix test for DeleteClaimCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClaimCommand.java
  src/test/java/seedu/address/logic/commands/DeleteClaimCommandTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.High

#156 Add missing colons
  src/main/java/seedu/address/logic/commands/AddClaimCommand.java
  src/main/java/seedu/address/logic/commands/CloseClaimCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClaimCommand.java
Labels: type.Bug

#170 Fix format issues in parseClaimAmount
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/insurance/claim/Claim.java
Labels: type.Bug

#171 Fix typo
  src/main/java/seedu/address/model/client/insurance/claim/Claim.java
Labels: type.Bug
